---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_20.04_instance
    image: ubuntu:20.04
    pre_build_image: false
  - name: ubuntu_18.04_instance
    image: ubuntu:18.04
    pre_build_image: false
provisioner:
  name: ansible
